### ISSUE TITLE
Consider renaming the effect to Network

### ISSUE THREAD

**Issue by arybczak** [Cajunvoodoo/network-effectful#1]
First of all, thanks for making the package :slightly_smiling_face: 

Is there any particular reason why the effect is called `SocketEff`, not `Network`? It wraps the `network` package after all.

**Comment by Cajunvoodoo** [comment]
It is called `SocketEff` because I was originally wrapping `socket`, not `network`. `Socket` for the effect name overlapped with `Socket` the... socket, but now that its a `network` wrapper, `Network` definitely makes a better name!

**Comment by Cajunvoodoo** [comment]
Fixed in [e096399](https://github.com/Cajunvoodoo/network-effectful/commit/e096399662ac430dc4f057b97fd4ffd890362365)
